class WorkflowStatus:
    NEW = "NEW"
    QUEUE = "QUEUE"
    START = "START"
    IN_SCOPE = "IN_SCOPE"
    NEED_CLARIFICATION = "NEED_CLARIFICATION"
    AWAITING_DIRECTION_CONFIRM = "AWAITING_DIRECTION_CONFIRM"
    IN_RESEARCH = "IN_RESEARCH"
    IN_REPORT = "IN_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class EventType:
    QUEUE = "QUEUE"
    SCOPE = "SCOPE"
    SUPERVISOR = "SUPERVISOR"
    RESEARCH = "RESEARCH"
    SEARCH = "SEARCH"
    REPORT = "REPORT"
    DIRECTION_CONFIRM = "DIRECTION_CONFIRM"
    ERROR = "ERROR"
